[package]
name = "mochidrop-torrent"
version = "1.0.0"
edition = "2021"

[dependencies]
librqbit = { version = "9.0.1", default-features = false, features = ["rust-tls"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "time"] }
